

services:
  api:
    build: .
    container_name: lyftr-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:////data/app.db
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      LOG_LEVEL: INFO
    volumes:
      - db-data:/data

volumes:
  db-data:
